# Spiral Matrix

Given the size, return a square matrix of numbers in spiral order.

The matrix should be filled with natural numbers, starting from 1
in the top-left corner, increasing in an inward, clockwise spiral order,
like these examples:

###### Spiral matrix of size 3

```text
1 2 3
8 9 4
7 6 5
```

###### Spiral matrix of size 4

```text
 1  2  3 4
12 13 14 5
11 16 15 6
10  9  8 7
```
## Source

Reddit r/dailyprogrammer challenge #320 [Easy] Spiral Ascension. [https://www.reddit.com/r/dailyprogrammer/comments/6i60lr/20170619_challenge_320_easy_spiral_ascension/](https://www.reddit.com/r/dailyprogrammer/comments/6i60lr/20170619_challenge_320_easy_spiral_ascension/)


## Version compatibility
This exercise has been tested on Julia versions >=1.0.

## Submitting Incomplete Solutions
It's possible to submit an incomplete solution so you can see how others have completed the exercise.


In [213]:
# submit
function spiral_printer(m)
    right(m) = [m[1,:], m[2:end,end]]
    shrink(m) = m[end:-1:2, end-1:-1:1]
    shrinker(acc, m) = isempty(m) ? vcat(acc[1:end-1]...) : shrinker(vcat(acc, m |> right), shrink(m))
    shrinker([],m)
end



function spiral_matrix(n::Int)
    to_matrix(a) = reshape(a, n, n) |> transpose
    
    
    (range(1,length=n^2)
        |> to_matrix
        |> spiral_printer
        |> xs -> zip(xs, range(1,length=n^2))
        |> collect
        |> xs -> sort(xs, by=first) 
        |> xs -> map(last,xs) 
        |> to_matrix)
end


spiral_matrix (generic function with 1 method)

In [214]:
using Test

# include("spiral-matrix.jl")


@testset "Different valid values" begin
    @testset "Empty spiral" begin
        @test spiral_matrix(0) == Matrix{Int}(undef,0,0)
    end
    @testset "Trivial spiral" begin
        @test spiral_matrix(1) == reshape([1],(1,1))
    end
    @testset "Spiral of size 2" begin
        @test spiral_matrix(2) == [1 2; 4 3]
    end
    @testset "Spiral of size 3" begin
        @test spiral_matrix(3) == [1 2 3; 8 9 4; 7 6 5]
    end
    @testset "Spiral of size 4" begin
        @test spiral_matrix(4) == [1 2 3 4; 12 13 14 5; 11 16 15 6; 10 9 8 7]
    end
    @testset "Spiral of size 5" begin
        @test spiral_matrix(5) == [1 2 3 4 5; 16 17 18 19 6; 15 24 25 20 7; 14 23 22 21 8; 13 12 11 10 9]
    end
end


Test Summary:          | Pass  Total
Different valid values |    6      6


Test.DefaultTestSet("Different valid values", Any[DefaultTestSet("Empty spiral", Any[], 1, false), DefaultTestSet("Trivial spiral", Any[], 1, false), DefaultTestSet("Spiral of size 2", Any[], 1, false), DefaultTestSet("Spiral of size 3", Any[], 1, false), DefaultTestSet("Spiral of size 4", Any[], 1, false), DefaultTestSet("Spiral of size 5", Any[], 1, false)], 0, false)

In [1]:
# To submit your exercise, you need to save your solution in a file called spiral-matrix.jl before using the CLI.
# You can either create it manually or use the following functions, which will automatically
# save every notebook cell starting with `# submit` in that file.

# Pkg.add("Exercism")
# using Exercism
# Exercism.create_submission("spiral-matrix")


In [2]:
Matrix{Int}(undef,0,0)

0×0 Array{Int64,2}

In [115]:
m =  [1 2 3 4; 12 13 14 5; 11 16 15 6; 10 9 8 7]

4×4 Array{Int64,2}:
  1   2   3  4
 12  13  14  5
 11  16  15  6
 10   9   8  7

In [116]:
m[end:-1:2, end-1:-1:1][end:-1:2, end-1:-1:1]

2×2 Array{Int64,2}:
 13  14
 16  15

spiralprinter (generic function with 1 method)

In [121]:
vcat([right(m), right(m[end:-1:2, end-1:-1:1]), right(m[end:-1:2, end-1:-1:1][end:-1:2, end-1:-1:1]),
right(m[end:-1:2, end-1:-1:1][end:-1:2, end-1:-1:1][end:-1:2, end-1:-1:1])]...)

8-element Array{Array{Int64,1},1}:
 [1, 2, 3, 4]
 [5, 6, 7]   
 [8, 9, 10]  
 [11, 12]    
 [13, 14]    
 [15]        
 [16]        
 []          

In [129]:
shrink(m) |> shrink |> shrink

1×1 Array{Int64,2}:
 16

In [187]:
m




4×4 Array{Int64,2}:
  1   2   3  4
 12  13  14  5
 11  16  15  6
 10   9   8  7

In [176]:
test = range(1,length=16) |> a -> reshape(a,4,4) |> transpose

4×4 LinearAlgebra.Transpose{Int64,Base.ReshapedArray{Int64,2,UnitRange{Int64},Tuple{}}}:
  1   2   3   4
  5   6   7   8
  9  10  11  12
 13  14  15  16

In [207]:
(zip(spiralprinter(test), range(1, length=16)) 
|> collect |> xs -> sort(xs, by=first) |> xs -> map(last,xs) |> a -> reshape(a,4,4) |> transpose)

4×4 LinearAlgebra.Transpose{Int64,Array{Int64,2}}:
  1   2   3  4
 12  13  14  5
 11  16  15  6
 10   9   8  7

In [1]:
spiralprinter(test)

UndefVarError: UndefVarError: spiralprinter not defined