# RNA Transcription

Given a DNA strand, return its RNA complement (per RNA transcription).

Both DNA and RNA strands are a sequence of nucleotides.

The four nucleotides found in DNA are adenine (**A**), cytosine (**C**),
guanine (**G**) and thymine (**T**).

The four nucleotides found in RNA are adenine (**A**), cytosine (**C**),
guanine (**G**) and uracil (**U**).

Given a DNA strand, its transcribed RNA strand is formed by replacing
each nucleotide with its complement:

* `G` -> `C`
* `C` -> `G`
* `T` -> `A`
* `A` -> `U`
## Source

Hyperphysics [http://hyperphysics.phy-astr.gsu.edu/hbase/Organic/transcription.html](http://hyperphysics.phy-astr.gsu.edu/hbase/Organic/transcription.html)


## Version compatibility
This exercise has been tested on Julia versions >=1.0.

## Submitting Incomplete Solutions
It's possible to submit an incomplete solution so you can see how others have completed the exercise.


In [28]:
# submit
function to_rna(dna::AbstractString)
    transcribe = Dict('G' => 'C', 'C' => 'G', 'T' => 'A', 'A' => 'U')
    dna |> collect |> xs -> map(dna_n -> get(transcribe,dna_n, :error), xs) |> 
        xs -> any(p -> p == :error, xs) ? throw(ErrorException("oops")) : xs |> join
end



to_rna (generic function with 1 method)

In [29]:
using Test

# include("rna-transcription.jl")

@testset "basic transformations" begin
    @testset "rna complement of cytosine is guanine" begin
      @test to_rna("C") == "G"
    end

    @testset "rna complement of guanine is cytosine" begin
      @test to_rna("G") == "C"
    end

    @testset "rna complement of thymine is adenine" begin
      @test to_rna("T") == "A"
    end

    @testset "rna complement of adenine is uracil" begin
      @test to_rna("A") == "U"
    end
end

@testset "rna complement" begin
    @test to_rna("ACGTGGTCTTAA") == "UGCACCAGAAUU"
end

@testset "error handling" begin
    @testset "dna correctly handles invalid input" begin
      @test_throws ErrorException to_rna("U")
    end

    @testset "dna correctly handles completely invalid input" begin
      @test_throws ErrorException to_rna("XXX")
    end

    @testset "dna correctly handles partially invalid input" begin
      @test_throws ErrorException to_rna("ACGTXXXCTTAA")
    end
end


Test Summary:         | Pass  Total
basic transformations |    4      4
Test Summary:  | Pass  Total
rna complement |    1      1
Test Summary:  | Pass  Total
error handling |    3      3


Test.DefaultTestSet("error handling", Any[DefaultTestSet("dna correctly handles invalid input", Any[], 1, false), DefaultTestSet("dna correctly handles completely invalid input", Any[], 1, false), DefaultTestSet("dna correctly handles partially invalid input", Any[], 1, false)], 0, false)

In [30]:
# To submit your exercise, you need to save your solution in a file called rna-transcription.jl before using the CLI.
# You can either create it manually or use the following functions, which will automatically
# save every notebook cell starting with `# submit` in that file.

# Pkg.add("Exercism")
using Exercism
Exercism.create_submission("rna-transcription")


255

In [20]:
?any

search: any Any any! code_warntype ReadOnlyMemoryError @code_warntype isreadonly



```
any(itr) -> Bool
```

Test whether any elements of a boolean collection are `true`, returning `true` as soon as the first `true` value in `itr` is encountered (short-circuiting).

If the input contains [`missing`](@ref) values, return `missing` if all non-missing values are `false` (or equivalently, if the input contains no `true` value), following [three-valued logic](https://en.wikipedia.org/wiki/Three-valued_logic).

# Examples

```jldoctest
julia> a = [true,false,false,true]
4-element Array{Bool,1}:
  true
 false
 false
  true

julia> any(a)
true

julia> any((println(i); v) for (i, v) in enumerate(a))
1
true

julia> any([missing, true])
true

julia> any([false, missing])
missing
```

---

```
any(p, itr) -> Bool
```

Determine whether predicate `p` returns `true` for any elements of `itr`, returning `true` as soon as the first item in `itr` for which `p` returns `true` is encountered (short-circuiting).

If the input contains [`missing`](@ref) values, return `missing` if all non-missing values are `false` (or equivalently, if the input contains no `true` value), following [three-valued logic](https://en.wikipedia.org/wiki/Three-valued_logic).

# Examples

```jldoctest
julia> any(i->(4<=i<=6), [3,5,7])
true

julia> any(i -> (println(i); i > 3), 1:10)
1
2
3
4
true

julia> any(i -> i > 0, [1, missing])
true

julia> any(i -> i > 0, [-1, missing])
missing

julia> any(i -> i > 0, [-1, 0])
false
```

---

```
any(A; dims)
```

Test whether any values along the given dimensions of an array are `true`.

# Examples

```jldoctest
julia> A = [true false; true false]
2×2 Array{Bool,2}:
 true  false
 true  false

julia> any(A, dims=1)
1×2 Array{Bool,2}:
 true  false

julia> any(A, dims=2)
2×1 Array{Bool,2}:
 true
 true
```


In [23]:
transcribe = Dict('G' => 'C', 'C' => 'G', 'T' => 'A', 'A' => 'U')
"ACGTGGTCTTAA" |> collect |> xs -> map(dna_n -> get(transcribe,dna_n, :error), xs) |> 
    xs -> any(p -> p == :error, xs) ? nothing : xs |> join

"UGCACCAGAAUU"

In [34]:
Dict([1,2,3] .=> [2,3,4])

Dict{Int64,Int64} with 3 entries:
  2 => 3
  3 => 4
  1 => 2