# Transpose

Given an input text output it transposed.

Roughly explained, the transpose of a matrix:

```text
ABC
DEF
```

is given by:

```text
AD
BE
CF
```

Rows become columns and columns become rows. See <https://en.wikipedia.org/wiki/Transpose>.

If the input has rows of different lengths, this is to be solved as follows:

- Pad to the left with spaces.
- Don't pad to the right.

Therefore, transposing this matrix:

```text
ABC
DE
```

results in:

```text
AD
BE
C
```

And transposing:

```text
AB
DEF
```

results in:

```text
AD
BE
 F
```

In general, all characters from the input should also be present in the transposed output.
That means that if a column in the input text contains only spaces on its bottom-most row(s),
the corresponding output row should contain the spaces in its right-most column(s).
## Source

Reddit r/dailyprogrammer challenge #270 [Easy]. [https://www.reddit.com/r/dailyprogrammer/comments/4msu2x/challenge_270_easy_transpose_the_input_text](https://www.reddit.com/r/dailyprogrammer/comments/4msu2x/challenge_270_easy_transpose_the_input_text)


## Version compatibility
This exercise has been tested on Julia versions >=1.0.

## Submitting Incomplete Solutions
It's possible to submit an incomplete solution so you can see how others have completed the exercise.


In [170]:
# submit

function pad(input)
    input != [] ? l = map(length, input) |> maximum : 0
    map(x -> vcat(collect(x), repeat([:nothing] ,(l - length(x)))), input)
end

function clean(output)
    l = findlast(x -> x != :nothing, vec(output)) 
    Iterators.take(vec(output), l) |> collect |> xs -> map(x -> x == :nothing ? " " : x,xs) |> join
end
    

function transpose_strings(input::AbstractArray)
    pad(input) |> xs -> map(collect,xs) |> x -> hcat(x...) |> eachrow |> xs -> map(clean,xs)
end


transpose_strings (generic function with 1 method)

In [171]:
using Test

# include("transpose.jl")

@testset "empty string" begin
    @test transpose_strings([]) == []
end

@testset "two characters in a row" begin
    @test transpose_strings(["A1"]) == ["A", "1"]
end

@testset "two characters in a column" begin
    @test transpose_strings(["A", "1"]) == ["A1"]
end

@testset "simple" begin
    @test transpose_strings(["ABC", "123"]) == [
          "A1",
          "B2",
          "C3"
        ]
end

@testset "single line" begin
    @test transpose_strings(["Single line."]) == [
          "S",
          "i",
          "n",
          "g",
          "l",
          "e",
          " ",
          "l",
          "i",
          "n",
          "e",
          "."
        ]
end

@testset "first line longer than second line" begin
    @test transpose_strings([
          "The fourth line.",
          "The fifth line."
        ]) == [
          "TT",
          "hh",
          "ee",
          "  ",
          "ff",
          "oi",
          "uf",
          "rt",
          "th",
          "h ",
          " l",
          "li",
          "in",
          "ne",
          "e.",
          "."
        ]
end

@testset "second line longer than first line" begin
    @test transpose_strings([
          "The first line.",
          "The second line."
        ]) == [
          "TT",
          "hh",
          "ee",
          "  ",
          "fs",
          "ie",
          "rc",
          "so",
          "tn",
          " d",
          "l ",
          "il",
          "ni",
          "en",
          ".e",
          " ."
        ]
end

@testset "square" begin
    @test transpose_strings([
          "HEART",
          "EMBER",
          "ABUSE",
          "RESIN",
          "TREND"
        ]) == [
          "HEART",
          "EMBER",
          "ABUSE",
          "RESIN",
          "TREND"
        ]
end

@testset "rectangle" begin
    @test transpose_strings([
          "FRACTURE",
          "OUTLINED",
          "BLOOMING",
          "SEPTETTE"
        ]) == [
          "FOBS",
          "RULE",
          "ATOP",
          "CLOT",
          "TIME",
          "UNIT",
          "RENT",
          "EDGE"
        ]
end

@testset "triangle" begin
    @test transpose_strings([
          "T",
          "EE",
          "AAA",
          "SSSS",
          "EEEEE",
          "RRRRRR"
        ]) == [
          "TEASER",
          " EASER",
          "  ASER",
          "   SER",
          "    ER",
          "     R"
        ]
end

@testset "many lines" begin
    @test transpose_strings([
          "Chor. Two households, both alike in dignity,",
          "In fair Verona, where we lay our scene,",
          "From ancient grudge break to new mutiny,",
          "Where civil blood makes civil hands unclean.",
          "From forth the fatal loins of these two foes",
          "A pair of star-cross'd lovers take their life;",
          "Whose misadventur'd piteous overthrows",
          "Doth with their death bury their parents' strife.",
          "The fearful passage of their death-mark'd love,",
          "And the continuance of their parents' rage,",
          "Which, but their children's end, naught could remove,",
          "Is now the two hours' traffic of our stage;",
          "The which if you with patient ears attend,",
          "What here shall miss, our toil shall strive to mend."
        ]) == [
          "CIFWFAWDTAWITW",
          "hnrhr hohnhshh",
          "o oeopotedi ea",
          "rfmrmash  cn t",
          ".a e ie fthow ",
          " ia fr weh,whh",
          "Trnco miae  ie",
          "w ciroitr btcr",
          "oVivtfshfcuhhe",
          " eeih a uote  ",
          "hrnl sdtln  is",
          "oot ttvh tttfh",
          "un bhaeepihw a",
          "saglernianeoyl",
          "e,ro -trsui ol",
          "h uofcu sarhu ",
          "owddarrdan o m",
          "lhg to'egccuwi",
          "deemasdaeehris",
          "sr als t  ists",
          ",ebk 'phool'h,",
          "  reldi ffd   ",
          "bweso tb  rtpo",
          "oea ileutterau",
          "t kcnoorhhnatr",
          "hl isvuyee'fi ",
          " atv es iisfet",
          "ayoior trr ino",
          "l  lfsoh  ecti",
          "ion   vedpn  l",
          "kuehtteieadoe ",
          "erwaharrar,fas",
          "   nekt te  rh",
          "ismdsehphnnosa",
          "ncuse ra-tau l",
          " et  tormsural",
          "dniuthwea'g t ",
          "iennwesnr hsts",
          "g,ycoi tkrttet",
          "n ,l r s'a anr",
          "i  ef  'dgcgdi",
          "t  aol   eoe,v",
          "y  nei sl,u; e",
          ",  .sf to l   ",
          "     e rv d  t",
          "     ; ie    o",
          "       f, r   ",
          "       e  e  m",
          "       .  m  e",
          "          o  n",
          "          v  d",
          "          e  .",
          "          ,"]
end


Test Summary: | Pass  Total
empty string  |    1      1
Test Summary:           | Pass  Total
two characters in a row |    1      1
Test Summary:              | Pass  Total
two characters in a column |    1      1
Test Summary: | Pass  Total
simple        |    1      1
Test Summary: | Pass  Total
single line   |    1      1
Test Summary:                      | Pass  Total
first line longer than second line |    1      1
Test Summary:                      | Pass  Total
second line longer than first line |    1      1
Test Summary: | Pass  Total
square        |    1      1
Test Summary: | Pass  Total
rectangle     |    1      1
Test Summary: | Pass  Total
triangle      |    1      1
Test Summary: | Pass  Total
many lines    |    1      1


Test.DefaultTestSet("many lines", Any[], 1, false)

In [1]:
# To submit your exercise, you need to save your solution in a file called transpose.jl before using the CLI.
# You can either create it manually or use the following functions, which will automatically
# save every notebook cell starting with `# submit` in that file.

# Pkg.add("Exercism")
# using Exercism
# Exercism.create_submission("transpose")



pad (generic function with 1 method)

In [135]:
?replace()

```
replace(A, old_new::Pair...; [count::Integer])
```

Return a copy of collection `A` where, for each pair `old=>new` in `old_new`, all occurrences of `old` are replaced by `new`. Equality is determined using [`isequal`](@ref). If `count` is specified, then replace at most `count` occurrences in total.

The element type of the result is chosen using promotion (see [`promote_type`](@ref)) based on the element type of `A` and on the types of the `new` values in pairs. If `count` is omitted and the element type of `A` is a `Union`, the element type of the result will not include singleton types which are replaced with values of a different type: for example, `Union{T,Missing}` will become `T` if `missing` is replaced.

See also [`replace!`](@ref).

# Examples

```jldoctest
julia> replace([1, 2, 1, 3], 1=>0, 2=>4, count=2)
4-element Array{Int64,1}:
 0
 4
 1
 3

julia> replace([1, missing], missing=>0)
2-element Array{Int64,1}:
 1
 0
```

---

```
replace(new::Function, A; [count::Integer])
```

Return a copy of `A` where each value `x` in `A` is replaced by `new(x)` If `count` is specified, then replace at most `count` values in total (replacements being defined as `new(x) !== x`).

# Examples

```jldoctest
julia> replace(x -> isodd(x) ? 2x : x, [1, 2, 3, 4])
4-element Array{Int64,1}:
 2
 2
 6
 4

julia> replace(Dict(1=>2, 3=>4)) do kv
           first(kv) < 3 ? first(kv)=>3 : kv
       end
Dict{Int64,Int64} with 2 entries:
  3 => 4
  1 => 3
```

---

```
replace(s::AbstractString, pat=>r; [count::Integer])
```

Search for the given pattern `pat` in `s`, and replace each occurrence with `r`. If `count` is provided, replace at most `count` occurrences. `pat` may be a single character, a vector or a set of characters, a string, or a regular expression. If `r` is a function, each occurrence is replaced with `r(s)` where `s` is the matched substring (when `pat`is a `Regex` or `AbstractString`) or character (when `pat` is an `AbstractChar` or a collection of `AbstractChar`). If `pat` is a regular expression and `r` is a [`SubstitutionString`](@ref), then capture group references in `r` are replaced with the corresponding matched text. To remove instances of `pat` from `string`, set `r` to the empty `String` (`""`).

# Examples

```jldoctest
julia> replace("Python is a programming language.", "Python" => "Julia")
"Julia is a programming language."

julia> replace("The quick foxes run quickly.", "quick" => "slow", count=1)
"The slow foxes run quickly."

julia> replace("The quick foxes run quickly.", "quick" => "", count=1)
"The  foxes run quickly."

julia> replace("The quick foxes run quickly.", r"fox(es)?" => s"bus\1")
"The quick buses run quickly."
```


In [110]:
function clean(output) 
   join(output)
end 

clean (generic function with 1 method)

In [118]:
transpose_strings(["abcd", "abcef", "abc"]) |> eachrow

Base.Generator{Base.OneTo{Int64},getfield(Base, Symbol("##175#176")){Array{Any,2}}}(getfield(Base, Symbol("##175#176")){Array{Any,2}}(Any['a' 'a' 'a'; 'b' 'b' 'b'; … ; 'd' 'e' :nothing; :nothing 'f' :nothing]), Base.OneTo(5))

In [169]:
clean([:nothing 'f' :nothing]);

UndefVarError: UndefVarError: ouput not defined

In [172]:
String[]

0-element Array{String,1}

" f"